/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gizwits_homey_utils_NDKJniUtils */

#ifndef _Included_com_gizwits_homey_utils_NDKJniUtils
#define _Included_com_gizwits_homey_utils_NDKJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    take
 * Signature: ([CI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_take
  (JNIEnv *, jobject, jcharArray, jint);

/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    analysisSession
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_analysisSession
  (JNIEnv *, jobject, jbyteArray);


/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    takeAck
 * Signature: ([B)[B[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_takeAck
        (JNIEnv *, jobject, jbyteArray,jbyteArray);
/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    getStatus
 * Signature: ([B)[B[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_getStatus
  (JNIEnv *, jobject, jbyteArray,jbyteArray);



/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    readNFC
 * Signature: ([CI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_readNFC
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    setNFC
 * Signature: ([B)[B[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_setNFC
        (JNIEnv *, jobject, jbyteArray,jbyteArray);



/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    unLock
 * Signature: ([B)[B[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_unLock
        (JNIEnv *, jobject, jbyteArray,jbyteArray);

/*
 * Class:     com_gizwits_homey_utils_NDKJniUtils
 * Method:    openKeyBox
 * Signature: ([B)[B[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gizwits_homey_utils_NDKJniUtils_openKeyBox
        (JNIEnv *, jobject, jbyteArray,jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
